const examB = [
{question:"La oxigenoterapia domiciliaria obliga a evitar:",options:["Tabaco","Agua","Reposo","Ventilación"],answer:0},
{question:"Las UPP aparecen por:",options:["Presión mantenida","Ejercicio","Movilidad","Hidratación"],answer:0},
{question:"La escala más usada para valorar UPP es:",options:["Norton","Apgar","Glasgow","Silverman"],answer:0},
{question:"La posición Fowler se usa principalmente para:",options:["Mejorar respiración","Mejorar visión","Curar heridas","Dormir"],answer:0},
{question:"El carcinoma pulmonar puede producir:",options:["Hemoptisis","Miopía","Otitis","Anisocoria"],answer:0},
{question:"La inmovilidad prolongada favorece:",options:["Rigidez","Flexibilidad","Autonomía","Fuerza"],answer:0},
{question:"El principal objetivo cambios posturales es:",options:["Prevenir UPP","Dormir","Relajar","Reducir visitas"],answer:0},
{question:"La bronquitis crónica se caracteriza por:",options:["Tos crónica","Diplopía","Otalgia","Disuria"],answer:0},
{question:"La piel húmeda aumenta riesgo de:",options:["Lesiones","Hipertensión","Hipoxia","Bronquitis"],answer:0},
{question:"El lavado manos debe hacerse:",options:["Antes y después contacto","Solo mañana","Solo noche","Nunca"],answer:0},
{question:"La cianosis suele observarse en:",options:["Labios","Rodillas","Cabello","Uñas pies exclusivamente"],answer:0},
{question:"El paciente encamado tiene riesgo de:",options:["Trombosis","Miopía","Otitis","Hipermetropía"],answer:0},
{question:"La principal función TCAE es:",options:["Cuidados básicos","Diagnóstico","Cirugía","Prescripción"],answer:0},
{question:"La comunicación terapéutica debe ser:",options:["Empática","Agresiva","Autoritaria","Despectiva"],answer:0},
{question:"La higiene íntima previene:",options:["Infecciones","Miopía","Otitis","Cefalea"],answer:0},
{question:"La dependencia en vestido significa:",options:["Necesita ayuda","Autonomía total","Alta","Reposo"],answer:0},
{question:"El oxígeno debe almacenarse:",options:["Lejos calor","Junto fuego","Sin ventilación","Cerca cocina"],answer:0},
{question:"Una ABVD es:",options:["Vestirse","Viajar","Comprar","Internet"],answer:0},
{question:"El paciente con disnea debe evitar:",options:["Esfuerzos intensos","Reposo relativo","Fowler","Ventilación"],answer:0},
{question:"La principal vía contagio hospitalario es:",options:["Contacto","Luz","Ropa","Cabello"],answer:0},
{question:"La hidratación adecuada favorece:",options:["Estado piel","Hipoxia","Miopía","Otitis"],answer:0},
{question:"La observación del TCAE debe registrar:",options:["Cambios estado","Diagnósticos","Cirugías","Prescripciones"],answer:0},
{question:"La movilización precoz mejora:",options:["Circulación","Miopía","Otitis","Visión"],answer:0},
{question:"La mejor medida prevención caídas es:",options:["Entorno seguro","Suelo mojado","Cables","Oscuridad"],answer:0},
{question:"La disnea puede acompañarse de:",options:["Taquipnea","Miopía","Otitis","Bradipsiquia"],answer:0},
{question:"La oxigenoterapia debe vigilar:",options:["Saturación","Color cabello","Longitud uñas","Vista"],answer:0},
{question:"La vida cama sillón favorece:",options:["Dependencia","Autonomía","Ejercicio","Movilidad"],answer:0},
{question:"La posición correcta para comer es:",options:["Sentado","Trendelenburg","Prono","Supino"],answer:0},
{question:"La higiene oral disminuye:",options:["Infecciones","HTA","Miopía","Otitis"],answer:0},
{question:"La principal complicación respiratoria es:",options:["Hipoxia","Miopía","Otitis","Escabiosis"],answer:0},
{question:"El trabajo equipo sanitario busca:",options:["Mejorar cuidados","Duplicar tareas","Conflictos","Desorganización"],answer:0},
{question:"El paciente fumador presenta riesgo aumentado de:",options:["Cáncer pulmón","Miopía","Otitis","Dermatitis"],answer:0},
{question:"La posición Fowler es aproximadamente:",options:["45-60 grados","0 grados","90 grados","180 grados"],answer:0},
{question:"La mejor medida para evitar infecciones es:",options:["Lavado manos","Perfume","Guantes sucios","Ventana cerrada"],answer:0},
{question:"La piel debe observarse para detectar:",options:["Enrojecimiento","Miopía","Otitis","Disfagia"],answer:0},
{question:"La autonomía personal mejora:",options:["Participación paciente","Sobreprotección","Inmovilidad","Aislamiento"],answer:0},
{question:"La sequedad mucosas se relaciona con:",options:["Oxigenoterapia","HTA","Miopía","Otitis"],answer:0},
{question:"La bronquitis crónica cursa con:",options:["Expectoración","Anisocoria","Disuria","Otalgia"],answer:0},
{question:"El TCAE debe mantener:",options:["Confidencialidad","Rumores","Burlas","Desprecio"],answer:0},
{question:"El uso absorbentes requiere:",options:["Cambios frecuentes","24h mismo","Sin higiene","Sin observación"],answer:0},
{question:"La mejor postura para respirar es:",options:["SemiFowler","Supino","Trendelenburg","Prono"],answer:0},
{question:"La hipertensión puede ser:",options:["Asintomática","Contagiosa","Dermatológica","Digestiva"],answer:0},
{question:"El paciente dependiente precisa:",options:["Supervisión ayuda","Aislamiento","Inmovilidad","Ignorar preferencias"],answer:0},
{question:"La principal finalidad higiene es:",options:["Bienestar","Castigo","Dependencia","Aislamiento"],answer:0},
{question:"La inmovilidad aumenta riesgo de:",options:["Estreñimiento","Hipermetropía","Otitis","Miopía"],answer:0},
{question:"La seguridad paciente incluye:",options:["Prevención riesgos","Ocultar errores","Sin registros","Ignorar incidencias"],answer:0},
{question:"La respiración dificultosa se denomina:",options:["Disnea","Apnea","Otalgia","Diplopía"],answer:0},
{question:"La observación respiratoria incluye:",options:["Frecuencia respiratoria","Color pelo","Tamaño pie","Vista"],answer:0},
{question:"La higiene manos clínica reduce:",options:["Transmisión microorganismos","Miopía","Otitis","Cefalea"],answer:0},
{question:"El principal objetivo atención sanitaria es:",options:["Bienestar seguridad","Castigo","Aislamiento","Dependencia"],answer:0}
];