const examC = [
{question:"La función principal del sistema respiratorio es:",options:["Intercambio gases","Digestión","Circulación","Filtración"],answer:0},
{question:"El oxígeno domiciliario debe mantenerse:",options:["Alejado calor","Junto cocina","Cerca tabaco","Sin ventilación"],answer:0},
{question:"La principal complicación del reposo prolongado es:",options:["UPP","Miopía","Otitis","Caries"],answer:0},
{question:"La posición Fowler mejora:",options:["Ventilación pulmonar","Digestión","Visión","Audición"],answer:0},
{question:"La bronquitis crónica afecta al sistema:",options:["Respiratorio","Digestivo","Nervioso","Renal"],answer:0},
{question:"La cianosis es coloración:",options:["Azulada","Roja","Amarilla","Verde"],answer:0},
{question:"La piel enrojecida puede indicar:",options:["UPP inicial","Miopía","Otitis","Hipoxia"],answer:0},
{question:"El TCAE colabora en:",options:["Cuidados básicos","Cirugía cardíaca","Diagnóstico","Prescripción"],answer:0},
{question:"La disnea puede empeorar con:",options:["Esfuerzo","Reposo","Fowler","Ventilación"],answer:0},
{question:"La mejor prevención UPP es:",options:["Cambios posturales","Inmovilidad","Fricción","Humedad"],answer:0},
{question:"La HTA significa:",options:["Hipertensión arterial","Hipotensión arterial","Hipoxia arterial","Hipertermia"],answer:0},
{question:"La movilización favorece:",options:["Circulación","Rigidez","Atrofia","Dependencia"],answer:0},
{question:"La oxigenoterapia puede resecar:",options:["Mucosas","Cabello","Uñas","Piel exclusivamente"],answer:0},
{question:"La principal medida prevención infecciones es:",options:["Higiene manos","Oscuridad","Reposo","Silencio"],answer:0},
{question:"La dependencia ABVD implica:",options:["Necesidad ayuda","Autonomía","Alta","Independencia"],answer:0},
{question:"La principal función cambios posturales es:",options:["Evitar UPP","Curar HTA","Reducir tos","Evitar visitas"],answer:0},
{question:"La tos con expectoración es típica de:",options:["Bronquitis crónica","Miopía","Otitis","Dermatitis"],answer:0},
{question:"El oxígeno favorece combustión por ser:",options:["Comburente","Antiséptico","Sedante","Analgésico"],answer:0},
{question:"La higiene oral previene:",options:["Infecciones","Miopía","Otitis","Hipotensión"],answer:0},
{question:"La vida cama sillón produce:",options:["Rigidez","Mayor movilidad","Autonomía","Fuerza"],answer:0},
{question:"La seguridad del paciente busca:",options:["Evitar daños","Aumentar riesgos","Reducir higiene","Ignorar incidencias"],answer:0},
{question:"La escucha activa requiere:",options:["Atención empatía","Interrumpir","Juzgar","Ignorar"],answer:0},
{question:"La comunicación profesional debe ser:",options:["Respetuosa","Agresiva","Despectiva","Autoritaria"],answer:0},
{question:"La mejor posición para descansar con disnea es:",options:["SemiFowler","Trendelenburg","Supino","Prono"],answer:0},
{question:"El lavado manos clínico debe realizarse:",options:["Antes después contacto","Solo mañana","Solo noche","Nunca"],answer:0},
{question:"La inmovilidad puede provocar:",options:["Trombosis","Miopía","Otitis","Glaucoma"],answer:0},
{question:"El paciente exfumador tiene riesgo aumentado de:",options:["Patología respiratoria","Otitis","Miopía","Escabiosis"],answer:0},
{question:"La hidratación piel previene:",options:["Lesiones","Hipoxia","HTA","Bronquitis"],answer:0},
{question:"La observación TCAE debe centrarse en:",options:["Cambios estado","Diagnósticos","Prescripciones","Cirugías"],answer:0},
{question:"La principal finalidad cuidados básicos es:",options:["Bienestar","Diagnóstico","Cirugía","Tratamiento médico"],answer:0},
{question:"El uso absorbentes requiere:",options:["Vigilancia piel","Ignorar humedad","Sin cambios","Fricción intensa"],answer:0},
{question:"La principal vía transmisión infecciones es:",options:["Contacto manos","Luz","Calzado","Cabello"],answer:0},
{question:"La movilización debe proteger:",options:["Ergonomía","Vista","Oído","Cabello"],answer:0},
{question:"La bronquitis crónica forma parte de:",options:["EPOC","ERC","DM","HTA"],answer:0},
{question:"La tos persistente debe:",options:["Vigilarse","Ignorarse","Ocultarse","Normalizarse siempre"],answer:0},
{question:"La autonomía paciente se fomenta:",options:["Según capacidades","Con sobreprotección","Anulando decisiones","Sin participación"],answer:0},
{question:"La posición supina en disnea grave es:",options:["Poco recomendable","Ideal","Obligatoria","La mejor"],answer:0},
{question:"La higiene íntima correcta previene:",options:["Infecciones","Miopía","Otitis","Hipotensión"],answer:0},
{question:"La respiración acelerada se llama:",options:["Taquipnea","Bradipnea","Apnea","Disfagia"],answer:0},
{question:"El TCAE debe respetar:",options:["Intimidad dignidad","Rumores","Burlas","Desprecio"],answer:0},
{question:"La oxigenoterapia debe revisarse según:",options:["Prescripción","Preferencia familiar","Horario TV","Comidas"],answer:0},
{question:"La principal complicación respiratoria es:",options:["Hipoxia","Miopía","Otitis","Escabiosis"],answer:0},
{question:"El paciente dependiente puede necesitar:",options:["Ayuda aseo","Cirugía","Diagnóstico","Prescripción"],answer:0},
{question:"La higiene diaria favorece:",options:["Bienestar","Aislamiento","Dependencia","Inmovilidad"],answer:0},
{question:"La observación piel incluye detectar:",options:["Enrojecimiento","Miopía","Otitis","Diplopía"],answer:0},
{question:"La principal prioridad clínica es:",options:["Respiración","Lectura","Visitas","Televisión"],answer:0},
{question:"La movilización adecuada mejora:",options:["Circulación","Rigidez","Atrofia","Dependencia"],answer:0},
{question:"La prevención caídas incluye:",options:["Entorno seguro","Suelo mojado","Cables","Oscuridad"],answer:0},
{question:"La higiene manos debe realizarse con:",options:["Agua jabón solución alcohólica","Solo agua","Perfume","Crema"],answer:0},
{question:"La confidencialidad implica:",options:["No divulgar información","Compartir rumores","Hablar pacientes","Ignorar privacidad"],answer:0},
{question:"El principal objetivo trabajo equipo es:",options:["Mejorar atención","Duplicar tareas","Reducir comunicación","Conflictos"],answer:0}
];